# List of networks to use for rebalancing
networks:
  ethereum:
    chainID: 1
    rpcURL: https://mainnet.infura.io/v3/<YOUR-PROJECT-ID>
  bsc:
    chainID: 56
    rpcURL: https://bsc-dataseed.binance.org/
  polygon:
    chainID: 137
    rpcURL: https://rpc-mainnet.matic.network

# List of tokens to use for rebalancing
tokens:
  usdt:
    # Token addresses for corresponding networks
    addresses:
      ethereum: 0x0000000000000000000000000000000000000001
      bsc: 0x0000000000000000000000000000000000000001
      polygon: 0x0000000000000000000000000000000000000001
    # Minimal net profit from rebalancing transaction. Specified in token decimals.
    # Potential profit lower than this value will be ignored.
    minimalProfit: 10000000000000000000
    # Optional. Enable infinite approve for rebalancing transactions.
    # Could help to speed up reward acquisition and reduce transaction costs.
    infiniteApprove: true

# List of accounts to use for rebalancing
accounts:
  default:
    privateKey: 0000000000000000000000000000000000000000000000000000000000000001

# List of interconnected liquidity pools used for rebalancing
pools:
  default:
    # Liquidity pool addresses for each network that bot wants to operate in
    addresses:
      ethereum: 0x0000000000000000000000000000000000000001
      bsc: 0x0000000000000000000000000000000000000001
      polygon: 0x0000000000000000000000000000000000000001
    # Tokens to support in this liquidity pool
    tokens: [usdt]
    # Accounts to use for rebalancing in this liquidity pool
    accounts: [default]
